In [1]:
import math
import numpy as np

In [2]:
def soft_max(i, Z):
    return math.e**Z[i] / np.sum(math.e**Z)

In [6]:
def calc(w, x, b):
    return np.dot(w, x.T) + b

In [28]:
X = np.array([[1, 3, -2]])
X.T

array([[ 1],
       [ 3],
       [-2]])

In [8]:
w1 = np.array([[0, -3, 1]])
b1 = 2

In [9]:
w2 = np.array([[1, 0, -1]])
b2 = -2

In [10]:
z1 = calc(w1, inputs, b1)
z1

array([[-9]])

In [11]:
z2 = calc(w2, inputs, b2)
z2

array([[1]])

In [22]:
Z = np.concatenate((z1, z2))
Z

array([[-9],
       [ 1]])

In [23]:
sm1 = soft_max(0, Z)
sm1

array([  4.53978687e-05])

In [26]:
sm2 = soft_max(1, Z)
sm2

array([ 0.9999546])